---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv-db
spec:
  storageClassName: {{ .Values.spec.storageClassName }}
{{- with .Values.spec.accessModes_db }}  
  accessModes:
    {{- toYaml . | nindent 4 }}
{{- end }}
  capacity:
    storage: {{ .Values.spec.capacity_1Gi }}
  hostPath:
    path: {{ .Values.spec.hostPath }}
