---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: {{ .Values.ports.protocol }}
      port: {{ .Values.ports.pg }}
      targetPort: {{ .Values.ports.pg }}
  type: {{ .Values.spec.type }}