---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fr
spec:
  selector:
    app: {{ .Release.Name }}-fr
  ports:
    - protocol: {{ .Values.ports.protocol }}
      port: {{ .Values.ports.front_80 }}
      targetPort: {{ .Values.ports.front_8000 }}
