---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: {{ .Values.spec.storageClassName }}
{{- with .Values.spec.accessModes_app }}
  accessModes:
    {{- toYaml . | nindent 4 }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.spec.capacity_500Mi }}