apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: app
spec:
  environments:
    stage:
      defaultNamespace: stage
      server: https://192.168.1.20:6443/
    prod:
      defaultNamespace: prod
      server: https://192.168.1.20:6443/
  vars: {}
