apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr
  labels:
    app: fr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fr
  template:
    metadata:
      labels:
        app: fr
    spec:
      containers:
      - name: fr
        image: foo4/13-kub-config-01-obj_src-frontend
        ports:
        - name: fr
          containerPort: 80
        env:
          - name: BASE_URL
            value: http://localhost:9000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: "/static"
            name: my-volume
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fr
spec:
  selector:
    app: fr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: my-nfs
# provisioner: cluster.local/nfs-server-nfs-server-provisioner
# parameters:
#   server: nfs-server.example.com
#   path: /static
#   readOnly: "false"
