apiVersion: apps/v1
kind: Deployment
metadata:
  name: fr-ba
  labels:
    app: fr-ba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fr-ba
  template:
    metadata:
      labels:
        app: fr-ba
    spec:
      containers:
      - name: fr
        image: foo4/13-kub-config-01-obj_src-frontend
        ports:
        - name: fr
          containerPort: 80
        env:
          - name: BASE_URL
            value: http://localhost:9000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: ba
        image: foo4/13-kub-config-01-obj_src-backend
        ports:
        - name: ba
          containerPort: 9000
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgres@db:5432/news
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
