---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-world-deployment
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        name: hello-world-app
