---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-logs
  namespace: default
subjects:
- kind: ServiceAccount
  name: loguser
  namespace: default
roleRef:
  kind: Role
  name: loguser-role
  apiGroup: rbac.authorization.k8s.io