---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loguser-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "describe", "logs"]
