resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    node01

    [node01]
    node01.netology.yc ansible_host=${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.node01
  ]
}
