source "yandex" "autogenerated_1" {
  disk_type           = "network-nvme"
  folder_id           = "b1g27gpcstr1l1bi3a22"
  image_description   = "by packer"
  image_family        = "centos"
  image_name          = "centos-7-base"
  source_image_family = "centos-7"
  ssh_username        = "centos"
  subnet_id           = "e9bo4l91g81obfpmhgpj"
  token               = ""
  use_ipv4_nat        = true
  zone                = "ru-central1-a"
}

build {
  sources = ["source.yandex.autogenerated_1"]

  provisioner "shell" {
    inline = ["sudo yum -y update", "sudo yum -y install bridge-utils bind-utils curl net-tools tcpdump rsync telnet openssh-server"]
  }

}